import type { User } from './auth';
import type { Club } from './club';
import type { Player } from './player';
import type { Field } from './venue';

export type MatchStatus = 'upcoming' | 'in_progress' | 'completed' | 'cancelled';

export type TeamSide = {
    name: string;
    color: string | null;
    logo_url: string | null;
    score: number | null;
};

export type MatchVideoUpload = {
    id: number;
    ulid: string;
    bunny_video_id: string;
    status: 'uploading' | 'encoding' | 'ready' | 'failed';
    original_filename: string | null;
    original_size_bytes: number | null;
    duration_seconds: number | null;
    video_offset_seconds: number;
    error_message: string | null;
    uploaded_at: string | null;
    encoded_at: string | null;
    stream_url?: string | null;
    embed_url?: string | null;
    thumbnail_url?: string | null;
    youtube_video_id?: string | null;
    youtube_url?: string | null;
    youtube_embed_url?: string | null;
    drive_file_id?: string | null;
    drive_embed_url?: string | null;
    video_stream_url?: string | null;
    bunny_deleted_at?: string | null;
};

export type FootballMatch = {
    id: number;
    ulid: string;
    club_id: number;
    field_id: number | null;
    title: string;
    scheduled_at: string;
    duration_minutes: number;
    arrival_minutes: number;
    max_players: number;
    max_substitutes: number;
    status: MatchStatus;
    share_token: string | null;
    registration_opens_hours: number;
    registration_opens_at: string | null;
    registration_closes_at: string | null;
    notes: string | null;
    video_upload?: MatchVideoUpload | null;
    active_video_service_request?: { status: 'pending' | 'contacted' | 'completed' | 'rejected' } | null;
    started_at: string | null;
    ended_at: string | null;
    stats_finalized_at: string | null;
    team_a_name: string;
    team_b_name: string;
    team_a_color: string | null;
    team_b_color: string | null;
    team_a_score: number | null;
    team_b_score: number | null;
    is_friendly: boolean;
    is_recurring: boolean;
    recurrence_days: number;
    auto_cancel: boolean;
    allow_outsiders: boolean;
    min_players_required: number;
    cancel_hours_before: number | null;
    club?: Club;
    field?: Field;
    season?: { id: number; name: string } | null;
    team_a?: { id: number; ulid: string; name: string; color: string | null; logo_url: string | null } | null;
    team_b?: { id: number; ulid: string; name: string; color: string | null; logo_url: string | null } | null;
    attendances?: MatchAttendance[];
    events?: MatchEvent[];
    attendances_count?: number;
    created_at: string;
    updated_at: string;
};

export type MatchAttendance = {
    id: number;
    ulid: string;
    match_id: number;
    player_id: number;
    status: 'confirmed' | 'declined' | 'waitlisted';
    role: 'pending' | 'starter' | 'substitute';
    team: 'a' | 'b' | null;
    confirmed_at: string | null;
    player?: Player;
    created_at: string;
    updated_at: string;
};

export type MatchEvent = {
    id: number;
    ulid: string;
    match_id: number;
    player_id: number | null;
    related_player_id: number | null;
    team: 'a' | 'b' | null;
    event_type: 'goal' | 'assist' | 'yellow_card' | 'red_card' | 'penalty_scored' | 'penalty_missed' | 'free_kick' | 'save' | 'own_goal' | 'substitution' | 'injury' | 'foul' | 'handball' | 'shot_on_target' | 'corner_kick' | 'throw_in' | 'offside' | 'team_foul' | 'team_handball' | 'team_penalty' | 'timeout' | 'ball_touched_referee' | 'stoppage_start' | 'stoppage_end' | 'water_break';
    minute: number;
    second: number;
    notes: string | null;
    highlighted: boolean;
    player?: Player;
    related_player?: Player;
    created_at: string;
    updated_at: string;
};

export type MatchReel = {
    id: number;
    ulid: string;
    match_id: number;
    event_id: number | null;
    player_id: number | null;
    requested_by: number | null;
    status: 'requested' | 'pending' | 'processing' | 'completed' | 'failed';
    source: 'auto' | 'manual' | 'request';
    title: string;
    start_second: number;
    end_second: number;
    duration: number;
    error_message: string | null;
    request_notes: string | null;
    processed_at: string | null;
    view_count: number;
    match?: FootballMatch;
    player?: Player;
    requester?: User;
    media_url?: string | null;
    created_at: string;
    updated_at: string;
};
